### ISSUE TITLE
Content inside the NotchKitWindow has user interaction disabled

### ISSUE THREAD

**Issue by ghost** [HarshilShah/NotchKit#1]
Nothing inside the NotchKitWindow's active display ares is intractable via touches. See the video (inside of the ZIP) for an example:

[NotchKitBug.mov](https://github.com/HarshilShah/NotchKit/files/1308747/NotchKitBug.zip)

**Comment by jacobwhite** [comment]
@roonieone I added `        safeView.isUserInteractionEnabled = false
` to NotchKitWindow.h > setup() to fix it.

**Comment by HarshilShah** [comment]
Fixed for the next release! Thanks!
