### ISSUE TITLE
Apps that use this technique will be rejected by Apple

### ISSUE THREAD

**Issue by KatkayApps** [HarshilShah/NotchKit#10]
Hi there, the idea is good but there is this tiny rule on the iPhone X Human Interface Guidelines...

> Don't mask or call special attention to key display features. Don't attempt to hide the device's rounded corners, sensor housing, or indicator for accessing the Home screen by placing black bars at the top and bottom of the screen. Don't use visual adornments like brackets, bezels, shapes, or instructional text to call special attention to these areas either.

https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

:(

**Comment by HarshilShah** [comment]
Read the ReadMe

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
