### ISSUE TITLE
Not available on cocoapods 

### ISSUE THREAD

**Issue by 4omar9** [HarshilShah/NotchKit#11]
## Not available on cocoapods

When i run "pod install" i get the following response:
[!] Unable to find a specification for `NotchKit`

- [x] I have reviewed the [`README`](https://github.com/HarshilShah/NotchKit/blob/master/README.md)
- [x] I have searched [existing issues](https://github.com/HarshilShah/NotchKit/issues) and this is not a duplicate

**Comment by HarshilShah** [comment]
I just made a new test project and its working here. You might need to run `pod repo update` to update CocoaPods' local cache 

<img width="683" alt="screen shot 2017-09-24 at 4 28 44 pm" src="https://user-images.githubusercontent.com/3503595/30781901-9c781e20-a145-11e7-8427-dca100328273.png">

**Comment by wjiuxing** [comment]
Is there any possibility of NotchKit to be used by cocoapods with "platform :ios, '9.0'" in Podfile?
Thanks.

$ pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `NotchKit (= 0.3.0)` required by `Podfile`

Specs satisfying the `NotchKit (= 0.3.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by HarshilShah** [comment]
@wjiuxing Working on it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
