### ISSUE TITLE
Content cut off

### ISSUE THREAD

**Issue by joshoconnor89** [HarshilShah/NotchKit#15]
Im getting an issue where the content at the top of my viewcontroller is being clipped b/c of NotchKit.  I was hoping that the library would shift the contents down instead of overlaying them.  B/c of this, I have to remove this library since it wont work for my app.  Hopefully in the future you plan on adding this in.

Cheers

## New issue checklist

- [x] I have reviewed the [`README`](https://github.com/HarshilShah/NotchKit/blob/master/README.md)
- [x] I have searched [existing issues](https://github.com/HarshilShah/NotchKit/issues) and this is not a duplicate

**Comment by HarshilShah** [comment]
This works as intended. NotchKit doesn’t touch your app’s layout at all, and it is not supposed to. It just, well, hides the notch (/status bar/home indicator)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshoconnor89** [comment]
Hm, well I dont think many people will be using this library then, since most apps use AutoLayout, I highly doubt people like myself are going to want to adjust every single constraint for every view since literally every view is clipped around the corners and sides.

Best regards

**Comment by HarshilShah** [comment]
Err, it seems you aren’t aware of the safeArea API introduced in iOS 11. Best of luck making your apps work on iPhone X without adjusting constraints

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshoconnor89** [comment]
Well now I am aware this library only works if you have safeArea enabled on the root view controller... All I had to do with check safe area in the interface builder and it works fine.  

Please add this to your documentation, I dont see anything about safe areas.

**Comment by HarshilShah** [comment]
Safe area is independent of this library. It’s how you’re supposed to lay out content as of iOS 11, so I don’t see any point to adding that

As for many people using this library, I did write a bit about that in the documentation, you might wanna check that 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
