### ISSUE TITLE
Apple Clearly Says This Is Not Allowed!

### ISSUE THREAD

**Issue by SudarshanMahesh** [HarshilShah/NotchKit#16]
**From Apple:**

> "Don't mask or call special attention to key display features. **_Don't attempt to hide the device's rounded corners, sensor housing, or indicator for accessing the Home screen by placing black bars at the top and bottom of the screen._** Don't use visual adornments like brackets, bezels, shapes, or instructional text to call special attention to these areas, either."

https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

**Comment by HarshilShah** [comment]
I Clearly Say This Is Not Allowed!

**From Me:**

> ## New issue checklist
>
> - [ ] I have reviewed the [`README`](https://github.com/HarshilShah/NotchKit/blob/master/README.md)
> - [ ] I have searched [existing issues](https://github.com/HarshilShah/NotchKit/issues) and this is not a duplicate

https://github.com/HarshilShah/NotchKit/blob/master/.github/ISSUE_TEMPLATE.md
