### ISSUE TITLE
Property 'maskedEdges' not found on object of type 'NotchKitW

### ISSUE THREAD

**Issue by sunyazhou13** [HarshilShah/NotchKit#17]
## New issue checklist

- [yes ] I have reviewed the [`README`](https://github.com/HarshilShah/NotchKit/blob/master/README.md)
- [yes] I have searched [existing issues](https://github.com/HarshilShah/NotchKit/issues) and this is not a duplicate

 if (@available(iOS 11, *)) {
        NotchKitWindow *notchWindow = [[NotchKitWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
//        [notchWindow setMaskedEdges:UIRectEdgeNone];
        notchWindow.maskedEdges = UIRectEdgeNone;
        self.window = notchWindow;
    } else {
        self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    }

error is Property 'maskedEdges' not found on object of type 'NotchKitWindow *' 

swift 4.0  var must add the  @objc refs  ==> https://stackoverflow.com/questions/45656671/unable-to-access-swift-class-from-objective-c-property-not-found-on-object-of

**Comment by HarshilShah** [comment]
Hi there, thanks for filing a bug.

This has been fixed in v0.4.2.
