### ISSUE TITLE
This concept might lead to App Store rejection

### ISSUE THREAD

**Issue by mwfire** [HarshilShah/NotchKit#3]
Hey there!

I really like the concept as it looks much cleaner! However, it seems to interfere with Apples [iOS Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x), where placing black bars at the top of the screen is to be explicitly avoided:

> Don't mask or call special attention to key display features. Don't attempt to hide the device's rounded corners, **sensor housing**, or indicator for accessing the Home screen by **placing black bars at the top and bottom of the screen**. Don't use visual adornments like brackets, bezels, shapes, or instructional text to call special attention to these areas either.

It might be worth mentioning this in the README, as this could lead to rejection by the Apple Store Review Team.

**Comment by HarshilShah** [comment]
Good point, I should've pointed to the HIG's recommendations. Will fix soon, thanks!

**Comment by mwfire** [comment]
Sure thing! :)

**Comment by HarshilShah** [comment]
And… done!
