### ISSUE TITLE
This violates Apple's iOS Human Interface Guidelines

### ISSUE THREAD

**Issue by MJLyco** [HarshilShah/NotchKit#5]
As the title states, this violate's Apple's guidelines and can lead to removal of an app form the app store.

> Don't mask or call special attention to key display features. Don't attempt to hide the device's rounded corners, sensor housing, or indicator for accessing the Home screen by placing black bars at the top and bottom of the screen. Don't use visual adornments like brackets, bezels, shapes, or instructional text to call special attention to these areas either.

Source: [https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/](url)

**Comment by HarshilShah** [comment]
This is addressed in both the ReadMe and #3. Please read those before filing a new issue
