### ISSUE TITLE
Landscape issue

### ISSUE THREAD

**Issue by Huang-Libo** [HarshilShah/NotchKit#7]
## Hi, NotchKit is a great framework, and it works well at portrait pages:
<img width="433" alt="portrait" src="https://user-images.githubusercontent.com/12227130/30687537-1db7754e-9eee-11e7-96f8-358712228cac.png">

## But it has some issue at Landscape page(Some view is cropped too much):

<img width="433" alt="landscape-error" src="https://user-images.githubusercontent.com/12227130/30687556-30a16bc4-9eee-11e7-94ed-e7b3a9a404b9.png">

## The origin Landscape page is look like this:
<img width="433" alt="landscape-correct" src="https://user-images.githubusercontent.com/12227130/30687563-370e52ce-9eee-11e7-8d08-978f28990957.png">

**Comment by HarshilShah** [comment]
That is working as designed. Layout of the bars is just done as per safe areas, and if you lay out your app's content as per the safe area as well it should fit the inside the bars added by NotchKit.

Alternatively, you can always turn this behaviour off by only masking the top and/or bottom bars using `maskedEdges` (see the ReadMe and the documentation in `NotchKitWindow.swift` for more info about that)
