### ISSUE TITLE
Against guidelines?

### ISSUE THREAD

**Issue by moochit** [HarshilShah/NotchKit#9]
From Apple guidelines:

> Don't attempt to hide the device's rounded corners, sensor housing, or indicator for accessing the Home screen by placing black bars at the top and bottom of the screen. Don't use visual adornments like brackets, bezels, shapes, or instructional text to call special attention to these areas either.

**Comment by HarshilShah** [comment]
Addressed in the ReadMe and multiple previous issues. Please read those before opening a new issue 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
